<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Configuration\**" />
    <Compile Remove="Views\Years\**" />
    <Compile Remove="wwwroot\assets\**" />
    <Content Remove="Data\Configuration\**" />
    <Content Remove="Views\Years\**" />
    <Content Remove="wwwroot\assets\**" />
    <EmbeddedResource Remove="Data\Configuration\**" />
    <EmbeddedResource Remove="Views\Years\**" />
    <EmbeddedResource Remove="wwwroot\assets\**" />
    <None Remove="Data\Configuration\**" />
    <None Remove="Views\Years\**" />
    <None Remove="wwwroot\assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.15" />
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Json" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.0.0" />
    <PackageReference Include="Serilog.UI" Version="3.1.0" />
  </ItemGroup>

</Project>
